### ISSUE TITLE
Make full use of osu!framework classes

### ISSUE THREAD

**Issue by LeNitrous** [vignette-project/vignette-application-live2d#3]
Currently, some calls are directly from OpenTK. This means we're bypassing optimizations implemented in `osu-framework`. The `CubismRenderingManager` class doesn't fully support this as the interface it provides for rendering manage one drawable at a time.

The framework provides `VertexBatch`, `VertexBuffer`, and `IVertex` classes and structs that we can use.

**Comment by sr229** [comment]
Is this still on the horizon? I think we should do performance tweaking in AB2 so I want this to be done once we're done with AB1.

**Comment by LeNitrous** [comment]
This is rather difficult to do. You'd need a full understanding how o!f handles graphics. Live2D isn't really doing impact performance-wise so it can be long-term.

**Comment by LeNitrous** [comment]
Attempted to write and found that it isn't feasible. The rewrite ongoing should help us performance-wise in the long run however.
