### ISSUE TITLE
Tangent values are not applying on Live2D model

### ISSUE THREAD

**Issue by sr229** [vignette-project/vignette-application-live2d#77]
Despite having us fixed the weird behavior on physics, mostly because MathF not being the same as CubismMath's logic, some tangent values aren't being applies. We're going to use the CubismSDK C++ API as basis for this since I believe it's another bug that roots from incorrect behavior again from MathF.

**Comment by LeNitrous** [comment]
Fixed in https://github.com/vignette-project/vignette-application-live2d/commit/a79f53a1b26a8c07caaec061407621405f741805.
